# trivia_questions.py

trivia_questions = [("Unscramble this TV show name:","https://scramble", ["Breaking Bad"]),
("Unscramble this TV show name:","https://scramble", ["Game of Thrones"]),
("Unscramble this TV show name:","https://scramble", ["The Sopranos"]),
("Unscramble this TV show name:","https://scramble", ["Friends"]),
("Unscramble this TV show name:","https://scramble", ["The Simpsons"]),
("Unscramble this TV show name:","https://scramble", ["Seinfeld"]),
("Unscramble this TV show name:","https://scramble", ["The Wire"]),
("Unscramble this TV show name:","https://scramble", ["Stranger Things"]),
("Unscramble this TV show name:","https://scramble", ["The Office (US)"]),
("Unscramble this TV show name:","https://scramble", ["M*A*S*H"]),
("Unscramble this TV show name:","https://scramble", ["The X-Files"]),
("Unscramble this TV show name:","https://scramble", ["Mad Men"]),
("Unscramble this TV show name:","https://scramble", ["The Mandalorian"]),
("Unscramble this TV show name:","https://scramble", ["I Love Lucy"]),
("Unscramble this TV show name:","https://scramble", ["Westworld"]),
("Unscramble this TV show name:","https://scramble", ["Twin Peaks"]),
("Unscramble this TV show name:","https://scramble", ["The Twilight Zone"]),
("Unscramble this TV show name:","https://scramble", ["House of Cards"]),
("Unscramble this TV show name:","https://scramble", ["Parks and Recreation"]),
("Unscramble this TV show name:","https://scramble", ["Fargo"]),
("Unscramble this TV show name:","https://scramble", ["Buffy the Vampire Slayer"]),
("Unscramble this TV show name:","https://scramble", ["Lost"]),
("Unscramble this TV show name:","https://scramble", ["Chernobyl"]),
("Unscramble this TV show name:","https://scramble", ["The Crown"]),
("Unscramble this TV show name:","https://scramble", ["Better Call Saul"]),
("Unscramble this TV show name:","https://scramble", ["Black Mirror"]),
("Unscramble this TV show name:","https://scramble", ["Star Trek: The Next Generation"]),
("Unscramble this TV show name:","https://scramble", ["Succession"]),
("Unscramble this TV show name:","https://scramble", ["The West Wing"]),
("Unscramble this TV show name:","https://scramble", ["Schitt’s Creek"]),
("Unscramble this TV show name:","https://scramble", ["Sherlock"]),
("Unscramble this TV show name:","https://scramble", ["Grey’s Anatomy"]),
("Unscramble this TV show name:","https://scramble", ["Saturday Night Live"]),
("Unscramble this TV show name:","https://scramble", ["The Big Bang Theory"]),
("Unscramble this TV show name:","https://scramble", ["How I Met Your Mother"]),
("Unscramble this TV show name:","https://scramble", ["Doctor Who"]),
("Unscramble this TV show name:","https://scramble", ["Homeland"]),
("Unscramble this TV show name:","https://scramble", ["Sons of Anarchy"]),
("Unscramble this TV show name:","https://scramble", ["Arrested Development"]),
("Unscramble this TV show name:","https://scramble", ["The Walking Dead"]),
("Unscramble this TV show name:","https://scramble", ["True Detective"]),
("Unscramble this TV show name:","https://scramble", ["Ozark"]),
("Unscramble this TV show name:","https://scramble", ["Friends"]),
("Unscramble this TV show name:","https://scramble", ["Peaky Blinders"]),
("Unscramble this TV show name:","https://scramble", ["Rick and Morty"]),
("Unscramble this TV show name:","https://scramble", ["Supernatural"]),
("Unscramble this TV show name:","https://scramble", ["Dexter"]),
("Unscramble this TV show name:","https://scramble", ["Cheers"]),
("Unscramble this TV show name:","https://scramble", ["Avatar: The Last Airbender"]),
("Unscramble this TV show name:","https://scramble", ["The Marvelous Mrs. Maisel"]),
("Unscramble this TV show name:","https://scramble", ["Fleabag"]),
("Unscramble this movie name:","https://scramble", ["The Godfather"]),
("Unscramble this movie name:","https://scramble", ["The Shawshank Redemption"]),
("Unscramble this movie name:","https://scramble", ["Star Wars: A New Hope"]),
("Unscramble this movie name:","https://scramble", ["The Dark Knight"]),
("Unscramble this movie name:","https://scramble", ["Pulp Fiction"]),
("Unscramble this movie name:","https://scramble", ["Titanic"]),
("Unscramble this movie name:","https://scramble", ["The Lord of the Rings: The Return of the King"]),
("Unscramble this movie name:","https://scramble", ["Forrest Gump"]),
("Unscramble this movie name:","https://scramble", ["Schindler’s List"]),
("Unscramble this movie name:","https://scramble", ["The Matrix"]),
("Unscramble this movie name:","https://scramble", ["Inception"]),
("Unscramble this movie name:","https://scramble", ["Fight Club"]),
("Unscramble this movie name:","https://scramble", ["The Empire Strikes Back"]),
("Unscramble this movie name:","https://scramble", ["Avengers: Endgame"]),
("Unscramble this movie name:","https://scramble", ["Jaws"]),
("Unscramble this movie name:","https://scramble", ["Goodfellas"]),
("Unscramble this movie name:","https://scramble", ["The Silence of the Lambs"]),
("Unscramble this movie name:","https://scramble", ["Saving Private Ryan"]),
("Unscramble this movie name:","https://scramble", ["Gladiator"]),
("Unscramble this movie name:","https://scramble", ["Jurassic Park"]),
("Unscramble this movie name:","https://scramble", ["Back to the Future"]),
("Unscramble this movie name:","https://scramble", ["The Lion King"]),
("Unscramble this movie name:","https://scramble", ["Raiders of the Lost Ark"]),
("Unscramble this movie name:","https://scramble", ["Casablanca"]),
("Unscramble this movie name:","https://scramble", ["Braveheart"]),
("Unscramble this movie name:","https://scramble", ["The Terminator"]),
("Unscramble this movie name:","https://scramble", ["Avatar"]),
("Unscramble this movie name:","https://scramble", ["The Social Network"]),
("Unscramble this movie name:","https://scramble", ["E.T. the Extra-Terrestrial"]),
("Unscramble this movie name:","https://scramble", ["The Avengers"]),
("Unscramble this movie name:","https://scramble", ["Gone with the Wind"]),
("Unscramble this movie name:","https://scramble", ["One Flew Over the Cuckoo's Nest"]),
("Unscramble this movie name:","https://scramble", ["Citizen Kane"]),
("Unscramble this movie name:","https://scramble", ["The Wizard of Oz"]),
("Unscramble this movie name:","https://scramble", ["The Prestige"]),
("Unscramble this movie name:","https://scramble", ["Apocalypse Now"]),
("Unscramble this movie name:","https://scramble", ["The Shining"]),
("Unscramble this movie name:","https://scramble", ["The Good", "the Bad", "and the Ugly"]),
("Unscramble this movie name:","https://scramble", ["Rocky"]),
("Unscramble this movie name:","https://scramble", ["12 Angry Men"]),
("Unscramble this movie name:","https://scramble", ["The Exorcist"]),
("Unscramble this movie name:","https://scramble", ["The Green Mile"]),
("Unscramble this movie name:","https://scramble", ["La La Land"]),
("Unscramble this movie name:","https://scramble", ["Interstellar"]),
("Unscramble this movie name:","https://scramble", ["Seven Samurai"]),
("Unscramble this movie name:","https://scramble", ["The Departed"]),
("Unscramble this movie name:","https://scramble", ["Once Upon a Time in Hollywood"]),
("Unscramble this movie name:","https://scramble", ["It's a Wonderful Life"]),
("Unscramble this movie name:","https://scramble", ["Mad Max: Fury Road"])
]  
