# trivia_questions.py

trivia_questions = [
("Unscramble this TV show name:","https://scramble5", ["Fargo"]),
("Unscramble this TV show name:","https://scramble5", ["Ozark"]),
("Unscramble this movie name:","https://scramble5", ["Rocky"]),
("Unscramble this TV show name:","https://scramble6", ["Dexter"]),
("Unscramble this TV show name:","https://scramble6", ["Cheers"]),
("Unscramble this movie name:","https://scramble6", ["Avatar"]),
("Unscramble this TV show name:","https://scramble7", ["Friends"]),
("Unscramble this TV show name:","https://scramble7", ["Mad Men"]),
("Unscramble this TV show name:","https://scramble7", ["Friends"]),
("Unscramble this TV show name:","https://scramble7", ["Fleabag"]),
("Unscramble this movie name:","https://scramble7", ["Titanic"]),
("Unscramble this TV show name:","https://scramble8", ["Seinfeld"]),
("Unscramble this TV show name:","https://scramble8", ["The Wire"]),
("Unscramble this TV show name:","https://scramble8", ["Sherlock"]),
("Unscramble this TV show name:","https://scramble8", ["Homeland"]),
("Unscramble this TV show name:","https://scramble9", ["Westworld"]),
("Unscramble this TV show name:","https://scramble9", ["Chernobyl"]),
("Unscramble this TV show name:","https://scramble9", ["The Crown"]),
("Unscramble this movie name:","https://scramble9", ["Inception"]),
("Unscramble this movie name:","https://scramble9", ["Gladiator"]),
("Unscramble this TV show name:","https://scramble10", ["Twin Peaks"]),
("Unscramble this TV show name:","https://scramble10", ["Succession"]),
("Unscramble this TV show name:","https://scramble10", ["Doctor Who"]),
("Unscramble this movie name:","https://scramble10", ["The Matrix"]),
("Unscramble this movie name:","https://scramble10", ["Fight Club"]),
("Unscramble this movie name:","https://scramble10", ["Goodfellas"]),
("Unscramble this movie name:","https://scramble10", ["Casablanca"]),
("Unscramble this movie name:","https://scramble10", ["Braveheart"]),
("Unscramble this movie name:","https://scramble10", ["La La Land"]),
("Unscramble this TV show name:","https://scramble11", ["The X Files"]),
("Unscramble this TV show name:","https://scramble11", ["I Love Lucy"]),
("Unscramble this movie name:","https://scramble11", ["The Shining"]),
("Unscramble this TV show name:","https://scramble12", ["Breaking Bad"]),
("Unscramble this TV show name:","https://scramble12", ["The Sopranos"]),
("Unscramble this TV show name:","https://scramble12", ["The Simpsons"]),
("Unscramble this TV show name:","https://scramble12", ["Black Mirror"]),
("Unscramble this TV show name:","https://scramble12", ["Supernatural"]),
("Unscramble this movie name:","https://scramble12", ["Pulp Fiction"]),
("Unscramble this movie name:","https://scramble12", ["Forrest Gump"]),
("Unscramble this movie name:","https://scramble12", ["The Avengers"]),
("Unscramble this movie name:","https://scramble12", ["Citizen Kane"]),
("Unscramble this movie name:","https://scramble12", ["The Prestige"]),
("Unscramble this movie name:","https://scramble12", ["12 Angry Men"]),
("Unscramble this movie name:","https://scramble12", ["The Exorcist"]),
("Unscramble this movie name:","https://scramble12", ["Interstellar"]),
("Unscramble this movie name:","https://scramble12", ["The Departed"]),
("Unscramble this TV show name:","https://scramble13", ["The West Wing"]),
("Unscramble this movie name:","https://scramble13", ["The Godfather"]),
("Unscramble this movie name:","https://scramble13", ["Jurassic Park"]),
("Unscramble this movie name:","https://scramble13", ["The Lion King"]),
("Unscramble this movie name:","https://scramble13", ["Seven Samurai"]),
("Unscramble this TV show name:","https://scramble14", ["House of Cards"]),
("Unscramble this TV show name:","https://scramble14", ["Schitt’s Creek"]),
("Unscramble this TV show name:","https://scramble14", ["Grey’s Anatomy"]),
("Unscramble this TV show name:","https://scramble14", ["True Detective"]),
("Unscramble this TV show name:","https://scramble14", ["Peaky Blinders"]),
("Unscramble this TV show name:","https://scramble14", ["Rick and Morty"]),
("Unscramble this movie name:","https://scramble14", ["The Terminator"]),
("Unscramble this movie name:","https://scramble14", ["Apocalypse Now"]),
("Unscramble this movie name:","https://scramble14", ["The Green Mile"]),
("Unscramble this actor's name:","https://scramble14", ["Shahrukh Khan", "Khan"])
]  
