# trivia_questions.py

trivia_questions = [
("Unscramble this TV show name:","https://scramble", ["Fargo"]),
("Unscramble this TV show name:","https://scramble", ["Ozark"]),
("Unscramble this movie name:","https://scramble", ["Rocky"]),
("Unscramble this TV show name:","https://scramble", ["Dexter"]),
("Unscramble this TV show name:","https://scramble", ["Cheers"]),
("Unscramble this movie name:","https://scramble", ["Avatar"]),
("Unscramble this TV show name:","https://scramble", ["Friends"]),
("Unscramble this TV show name:","https://scramble", ["Mad Men"]),
("Unscramble this TV show name:","https://scramble", ["Friends"]),
("Unscramble this TV show name:","https://scramble", ["Fleabag"]),
("Unscramble this movie name:","https://scramble", ["Titanic"]),
("Unscramble this TV show name:","https://scramble", ["Seinfeld"]),
("Unscramble this TV show name:","https://scramble", ["The Wire"]),
("Unscramble this TV show name:","https://scramble", ["Sherlock"]),
("Unscramble this TV show name:","https://scramble", ["Homeland"]),
("Unscramble this TV show name:","https://scramble", ["Westworld"]),
("Unscramble this TV show name:","https://scramble", ["Chernobyl"]),
("Unscramble this TV show name:","https://scramble", ["The Crown"]),
("Unscramble this movie name:","https://scramble", ["Inception"]),
("Unscramble this movie name:","https://scramble", ["Gladiator"]),
("Unscramble this TV show name:","https://scramble", ["Twin Peaks"]),
("Unscramble this TV show name:","https://scramble", ["Succession"]),
("Unscramble this TV show name:","https://scramble", ["Doctor Who"]),
("Unscramble this movie name:","https://scramble", ["The Matrix"]),
("Unscramble this movie name:","https://scramble", ["Fight Club"]),
("Unscramble this movie name:","https://scramble", ["Goodfellas"]),
("Unscramble this movie name:","https://scramble", ["Casablanca"]),
("Unscramble this movie name:","https://scramble", ["Braveheart"]),
("Unscramble this movie name:","https://scramble", ["La La Land"]),
("Unscramble this TV show name:","https://scramble", ["The X-Files"]),
("Unscramble this TV show name:","https://scramble", ["I Love Lucy"]),
("Unscramble this movie name:","https://scramble", ["The Shining"]),
("Unscramble this TV show name:","https://scramble", ["Breaking Bad"]),
("Unscramble this TV show name:","https://scramble", ["The Sopranos"]),
("Unscramble this TV show name:","https://scramble", ["The Simpsons"]),
("Unscramble this TV show name:","https://scramble", ["Black Mirror"]),
("Unscramble this TV show name:","https://scramble", ["Supernatural"]),
("Unscramble this movie name:","https://scramble", ["Pulp Fiction"]),
("Unscramble this movie name:","https://scramble", ["Forrest Gump"]),
("Unscramble this movie name:","https://scramble", ["The Avengers"]),
("Unscramble this movie name:","https://scramble", ["Citizen Kane"]),
("Unscramble this movie name:","https://scramble", ["The Prestige"]),
("Unscramble this movie name:","https://scramble", ["12 Angry Men"]),
("Unscramble this movie name:","https://scramble", ["The Exorcist"]),
("Unscramble this movie name:","https://scramble", ["Interstellar"]),
("Unscramble this movie name:","https://scramble", ["The Departed"]),
("Unscramble this TV show name:","https://scramble", ["The West Wing"]),
("Unscramble this movie name:","https://scramble", ["The Godfather"]),
("Unscramble this movie name:","https://scramble", ["Jurassic Park"]),
("Unscramble this movie name:","https://scramble", ["The Lion King"]),
("Unscramble this movie name:","https://scramble", ["Seven Samurai"]),
("Unscramble this TV show name:","https://scramble", ["House of Cards"]),
("Unscramble this TV show name:","https://scramble", ["Schitt’s Creek"]),
("Unscramble this TV show name:","https://scramble", ["Grey’s Anatomy"]),
("Unscramble this TV show name:","https://scramble", ["True Detective"]),
("Unscramble this TV show name:","https://scramble", ["Peaky Blinders"]),
("Unscramble this TV show name:","https://scramble", ["Rick and Morty"]),
("Unscramble this movie name:","https://scramble", ["The Terminator"]),
("Unscramble this movie name:","https://scramble", ["Apocalypse Now"]),
("Unscramble this movie name:","https://scramble", ["The Green Mile"]),
("Unscramble this actor's name:","https://scramble", ["Shahrukh Khan", "Khan"])
]  
